CODEOWNERS
The Onboarding team is starting to contribute and maintain templates in this directory. Adding this team as codeowners to help manage this repository. 
See team here: https://github.com/orgs/sysdiglabs/teams/team-secure-onboarding/members
=> Add Onboarding team as Codeowners

CODEOWNERS, templates_cspm_eventbridge/OrgFullInstall.yaml, templates_eventbridge/EventBridge.yaml, templates_eventbridge/OrgEventBridge.yaml
Add multiregion support for EventBridge and Full install flows by creating two stacksets. One to create global resources in a single region, and one to create regional resources in multiple regions.
=> Support multiregion EB

templates_cspm/CloudAgentlessRole.yaml, templates_cspm/OrgCloudAgentlessRole.yaml, templates_cspm_eventbridge/FullInstall.yaml, templates_cspm_eventbridge/OrgFullInstall.yaml, templates_eventbridge/EventBridge.yaml, templates_eventbridge/OrgEventBridge.yaml
Tested this out and there is a race condition where if `MgmtAccEBRuleStackSet` is created before `AdministrationRole`, the stackset fails to create. This PR makes `MgmtAccEBRuleStackSet` directly depend on `AdministrationRole`, which ensures the resources are created in the right order.
Fixes a bug where role stacksets were applied to all regions instead of just one
Removes default role names
It also includes some simplifications such as removing `Path: /` (which is [the default](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-path)), and `${AWS::Partition}` (since we don't support china or gov cloud)
=> Resolve race condition, apply roles in single region

templates_cspm_eventbridge/OrgFullInstall.yaml, templates_eventbridge/OrgEventBridge.yaml
adds an explicit dependency between MgmtAccEBRuleStackSet and associated self managed roles Even though there is an implicit dependency because of the use of Fn::GetAtt, we also need an explicit dependency to handle stack teardown gracefully. Adds cfn-lint exclusion
=> fix: self managed stackset dependencies

.github/workflows/ci-master-cloudlogs.yaml, .github/workflows/ci-master-full-install-with-cloudlogs.yaml, .github/workflows/ci-pull-request-cloudlogs.yaml, .github/workflows/ci-pull-request-full-install-with-cloudlogs.yaml, templates_cloudlogs/CloudLogs.yaml, templates_cloudlogs/Makefile, templates_cspm_cloudlogs/FullInstall.yaml, templates_cspm_cloudlogs/Makefile, templates_cspm_cloudlogs/OrgFullInstall.yaml
Add the `cloudlogs` module for AWS onboarding. The template provisions a dedicated role to be assumed by Sysdig's trusted identity that has `Get` and `List` permissions on a CloudTrail-backed S3 bucket. 
The corresponding `terraform` implementation can be found [here](https://github.com/draios/terraform-aws-secure-for-cloud/tree/main/modules/services/cloud-logs). 
**Note for the reviewers**: In the `CloudLogs` single case only one template is needed for both the `single` and `org` cases, that's why the s3 path in the `Makefile` does not use the `/single/` component on the file keys. Please let me know if I've missed anything or if you prefer other conventions!
=> Add CloudLogs module for AWS Onboarding 

templates_cloudlogs/CloudLogs.yaml, templates_cspm_cloudlogs/FullInstall.yaml, templates_cspm_cloudlogs/OrgFullInstall.yaml
Small PR to revert to the old naming convention for the `ExternalID` parameter. This is necessary to properly propagate the value throughout the onboarding flow.
=> Revert to ExternalID naming convention

templates_cspm_cloudlogs/Makefile
cloudlogs-cspm CI was incorrectly deleting the eventbridge-cspm templates.
=> Delete correct templates in cloudlogs-cspm CI

templates_cloudlogs/CloudLogs.yaml, templates_cloudlogs/Makefile, templates_cloudlogs/OrgCloudLogs.yaml, templates_cspm_cloudlogs/OrgFullInstall.yaml
Revamp `CloudLogs` templates in order to provision all the necessary resoruces to fully support the organizational case. Now the end result is the same as applying the alternative `terraform` module(s).
Note that, before this change, only one `CloudLogs` template was used for both the `Single` and `Organization` case, while an additional role needed to be provisioned in the `Organizational` case for Sysdig's systems to properly work. This means that also the `Makefile` taking care of publishing the templates has been updated accordingly, along with the necessary changes in Sysdig's backend.
=> Revamp cloudformation templates for Cloudlogs module

.github/workflows/ci-master-cloudlogs.yaml, .github/workflows/ci-pull-request-cloudlogs.yaml
Add `ci-org` build step in `ci-master-cloudlogs.yml` and `ci-pull-request-cloudlogs.yml`
=> Update cloudlogs workflow in order to publish org template

templates_cloudlogs/CloudLogs.yaml, templates_cloudlogs/Makefile, templates_cloudlogs/OrgCloudLogs.yaml, templates_cspm_cloudlogs/FullInstall.yaml, templates_cspm_cloudlogs/OrgFullInstall.yaml
The update to the S3 policy is necessary to properly access the audit logs stored in S3 covering all the corner cases.
=> Update S3 access policy in cloudlogs-related templates

templates_cspm_eventbridge/FullInstall.yaml, templates_cspm_eventbridge/OrgFullInstall.yaml, templates_eventbridge/EventBridge.yaml, templates_eventbridge/OrgEventBridge.yaml
Adding the following permissions to EB role to be able to run thorough validations. These permissions are read-only and targetted to only specific EB rule resource created by the same CFT template :-
- events:DescribeRule
- events:ListTargetsByRule
Note:
- Fixing this for both single and org onboarding case.
- Validated the CFT templates using make validate.
=> fix(eventbridge): Add permissions to describe rule and targets to CFTs

templates_cspm/CloudAgentlessRole.yaml, templates_cspm/OrgCloudAgentlessRole.yaml, templates_cspm_cloudlogs/FullInstall.yaml, templates_cspm_cloudlogs/OrgFullInstall.yaml, templates_cspm_eventbridge/FullInstall.yaml, templates_cspm_eventbridge/OrgFullInstall.yaml
Removing `account:GetContactInformation` since it is no longer a required permission for the CSPM feature to work.
Adding `macie2:ListClassificationJobs` permission.
=> Update permissions in AWS trust-relationship CFT templates

templates_cspm/CloudAgentlessRole.yaml, templates_cspm/OrgCloudAgentlessRole.yaml, templates_cspm_cloudlogs/FullInstall.yaml, templates_cspm_cloudlogs/OrgFullInstall.yaml, templates_cspm_eventbridge/FullInstall.yaml, templates_cspm_eventbridge/OrgFullInstall.yaml
Adding permissions in order to obtain an aws lambda as docker image pull string which is only accessible through the GetFunction call (collector change incoming).
=> [SSPROD-40004] Adding permissions for aws-templates for the getFunction call

templates_cspm_cloudlogs/OrgFullInstall.yaml, templates_cspm_eventbridge/OrgFullInstall.yaml, templates_eventbridge/OrgEventBridge.yaml
Add region parallelism to all stacksets. This was added in TF but missing in these CFTs.
Also set the default concurrency count to 10 to match the TF
=> Add region parallelism to stacksets

templates_cspm_cloudlogs/OrgFullInstall.yaml, templates_cspm_eventbridge/OrgFullInstall.yaml, templates_eventbridge/OrgEventBridge.yaml
For all stacksets, use:
- `MaxConcurrentPercentage: 100`
- `ConcurrencyMode: SOFT_FAILURE_TOLERANCE`
`FailureTolerancePercentage` is not set (and thus defaults to `0`) intentionally, and there are no downstream processes that are blocked by the CFT operation failing, and thus will give more visibility for failures without compromising the rest of the install experience.
=> Use 100% concurrency

modules/Makefile, modules/foundational.cft.yaml, modules/log_ingestion.events.cft.yaml, modules/log_ingestion.s3.cft.yaml
Change summary:
-------------------
- Added support to install govcloud single account and org in foundational template.
- Added same support in log_ingestion event-bridge template.
- For log_ingestion s3, no changes required to the template. Added minor nits.
Testing done:
----------------
With the UI PR changes was able to test below,
Single AWS Govcloud account,
- Foundational onboarding - ✅ 
- CDR install with EB - Unsupported (CFT stack creation & BE block this as expected) - ✅ 
- CDR install with S3 -  ✅ 
AWS Govcloud Org,
- Foundational onboarding -  ✅
- CDR install with EB - Unsupported (CFT stack creation & BE block this as expected) -  ✅ 
- CDR install with S3 - NA
=> feat(modules): Support for Govcloud account/org

modules/vm_workload_scanning.cft.yaml
https://sysdigcloud.slack.com/archives/CMCPMSQ8Y/p1738853886784009
Hi team, Covantis POV here. We onboarded AWS org via CFT CSPM+CDR/CIEM+WorkloadScanning
I think the CFT template we use for WorkloadScanning does not create the required role sysdig-vm-workload-scanning-xxxxx in the management account (1st screenshot). I was able to replicate that in our lab aws org, I don't see the role in the list of resources created by the stack (2nd screenshot), just the stackset that will be used for sub-accounts.
Can you please check? [cc 
[@Stefan Trimborn](https://sysdigcloud.slack.com/team/U036WTW25AT)
] (edited)
=> fix(vm-workload-scanning): Fixing CFT for Managament Account for Workload Scanning [SSPROD-52797]

modules/log_ingestion.events.cft.yaml
on AWS EB CFT templates, split sysdig required settings and user input parameters
=> fix(aws): template for eb and s3

.github/workflows/ci-modules.yaml, modules/Makefile, modules/README.md, modules/foundational.cft.yaml, modules/log_ingestion.events.cft.yaml, modules/vm_workload_scanning.cft.yaml, modules/volume_access.cft.yaml
[under testing]
Change summary:
----------------
Adding new CFT template parameters to support include OUs and include/exclude accounts.
=> feat(modules): Support for include/exclude parameters

modules/log_ingestion.s3.cft.yaml
Support cross-region and cross-accounts deployments for Cloud Logs integration
Changes:
- Stackset for cross accounts bucket
- Stackset for cross accounts topic
- Update documentation
This allows the module to work correctly when the S3 bucket and SNS topic are in different regions
=> feat(cloudlogs): add cross account support

modules/Makefile, modules/log_ingestion.events.cft.yaml
This pull request introduces significant changes to the `modules/log_ingestion.events.cft.yaml` file, focusing on replacing the `TargetEventBusARN` parameter with new parameters related to API authentication and ingestion for Sysdig Secure. The main changes include adding new parameters (`ApiKey`, `IngestionUrl`, `RateLimit`), updating resource definitions, and modifying IAM policies.
* Added new parameters: `ApiKey`, `IngestionUrl`, and `RateLimit` to replace `TargetEventBusARN` for API authentication and ingestion. [[1]](diffhunk://#diff-07a5e583f6827ac7d790e2f4c6ea78ced6796b464a3227a814ba23763ff931b8L16-R18) [[2]](diffhunk://#diff-07a5e583f6827ac7d790e2f4c6ea78ced6796b464a3227a814ba23763ff931b8L33-R40) [[3]](diffhunk://#diff-07a5e583f6827ac7d790e2f4c6ea78ced6796b464a3227a814ba23763ff931 …
=> feat(event-bridge): change cft to create api dest (SSPROD-53940)

modules/log_ingestion.s3.cft.yaml
* replace OrganizationalUnitIds parameter with rootOUID
=> feat(cloudlogs): replace OrganizationalUnitIds with rootOUID

modules/log_ingestion.s3.cft.yaml
* Make the KMS Account ID and KMS Arn parameters optionals
=> fix(cloud_logs): optional KMS encryption key
